//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveMyHome {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesSource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesSource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaveMyHome.MessagesSource", typeof(MessagesSource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша квартира находится на 1-м этаже, поэтому вы не можете никого затопить!.
        /// </summary>
        internal static string ForFirstFloorUser {
            get {
                return ResourceManager.GetString("ForFirstFloorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша квартира находится на Последнем этаже, поэтому Вас никто не может затопить! Возможно, у Вас протекает крыша. Попробуйте обратиться в коммунальную службу!.
        /// </summary>
        internal static string ForLastFloorUser {
            get {
                return ResourceManager.GetString("ForLastFloorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемые соседи, в моей квартире произошла утечка воды. Проверьте, пожалуйста, нет ли следов затопления в Ваших квартирах!.
        /// </summary>
        internal static string CulpritHeadMessage {
            get {
                return ResourceManager.GetString("CulpritHeadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше сообщение успешно отправлено.
        /// </summary>
        internal static string MessageIsSent {
            get {
                return ResourceManager.GetString("MessageIsSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проблема зафиксирована.
        /// </summary>
        internal static string ProblemIsFixed {
            get {
                return ResourceManager.GetString("ProblemIsFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уважаемые соседи, в моей квартире появились следы воды извне. Проверьте, пожалуйста, нет ли утечки воды в Ваших квартирах!.
        /// </summary>
        internal static string VictimHeadMessage {
            get {
                return ResourceManager.GetString("VictimHeadMessage", resourceCulture);
            }
        }
    }
}
